name: APIClient

options:
  bundleIdPrefix: dev.jano.apiclient
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.4

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

packages:

  Report:
    url: git@github.com:janodevorg/Report.git
    branch: main

targets:

  APIClient:
    dependencies:
      - package: Report
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - APIClientTests
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.4
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.apiclient
       PRODUCT_NAME: APIClient
    sources: 
       - sources/main
    type: framework

  APIClientTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 15.4
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.apiclient.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: APIClient
